### PR TITLE
Amend checks when moves are involved

### LINKED ISSUE #1665: We cannot amend a rearrangement session with a normal session
Currently we don't support calling amend to "merge" a move session with a normal session. This can be seen in a `FIXME` in transaction_log.rs: `// FIXME: verify no moves in origins`.

We need to add checks for this, make sure it never happens, and fail nicely. Optionally amending a move with another move could be fine, but support for this would be optional for now I think

### PR DESCRIPTION
**Pull request by li-em**
Fix #1665

Move the previous transaction log check to the beginning of `do_flush`, avoid doing all the work before failing if amending with regular and rearrange sessions.

### CODE REVIEW

File: icechunk/src/session.rs [hunk 1]
```diff
@@ -4389,6 +4419,45 @@ mod tests {
...
+        let mut session = repo.writable_session("main").await?;
+        session
+            .add_group("/fail".try_into().unwrap(), Bytes::copy_from_slice(b""))
+            .await?;
+        let result = session.amend("amend after move", None, false).await;
+        assert!(result.is_err());
+        let err = result.unwrap_err();
+        assert!(matches!(err.kind, SessionErrorKind::RearrangeSessionOnly));
+
+        // Rearrange session, amend on top of a move commit: should fail?
```
Comment (dcherian) [inline icechunk/src/session.rs]:
```suggestion
        // Rearrange session, amend on top of a move commit
```
