### PR TITLE
Make V2 branch expiration behaviour match V1

### LINKED ISSUE #1421: Extend python stateteful test to cover expiration/gc on IC1 repos

### LINKED ISSUE #1520: Difference in v1 vs v2 branch expiration
### What happened?

icechunk v2 spec version 2 has different behavior for expiring branches compared to all other combinations.

When both feature and main point to the same commit (which is old enough to be expired) then the v2/2 combo will not expire the feature branch, but other versions will

```
=== Same tip (both point to commit2) ===
v1 python: ['feature', 'main'] -> expired 2 snapshots -> remaining branches: ['main']
v2 spec=1: ['feature', 'main'] -> expired 2 snapshots -> remaining branches: ['main']
v2 spec=2: ['feature', 'main'] -> expired 1 snapshots -> remaining branches: ['feature', 'main']

=== Separate tips (feature->commit1, main->commit2) ===
v1 python: ['feature', 'main'] -> expired 2 snapshots -> remaining branches: ['main']
v2 spec=1: ['feature', 'main'] -> expired 2 snapshots -> remaining branches: ['main']
v2 spec=2: ['feature', 'main'] -> expired 1 snapshots -> remaining branches: ['main']
```

### What did you expect to happen?

I guess consistency in expiring feature, or none of the other combos expire.

### Minimal Complete Verifiable Example

```Python
#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "icechunk>=2.0.0.dev0",
#     "icechunk_v1",
#     "zarr>=3",
# ]
#
# [tool.uv]
# extra-index-url = [
#     "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple",
#     "http://127.0.0.1:8123/simple/",
# ]
# index-strategy = "unsafe-best-match"
# ///

"""
Requires the wheel-rename proxy server running:
    uvx --from "wheel-rename[server] @ git+https://github.com/earth-mover/rename-wheel" \
        wheel-rename serve \
        -u https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
        -r "icechunk=icechunk_v1:<2" \
        --port 8123
"""

import datetime
import icechunk
import icechunk_v1
import zarr

future = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=1)


def test_expire(name, repo, separate_tips=False):
    session = repo.writable_session("main")
    root = zarr.open_group(session.store, mode="a")
    root.create_array("arr", shape=(2,), dtype="i4")
    commit1 = session.commit("first")

    if separate_tips:
        # feature at commit1, main continues to commit2
        repo.create_branch("feature", commit1)
        session = repo.writable_session("main")
        zarr.open_group(session.store, mode="a")["arr"][:] = [1, 2]
        session.commit("second")
    else:
        # Both branches point to same commit
        session = repo.writable_session("main")
        zarr.open_group(session.store, mode="a")["arr"][:] = [1, 2]
        commit2 = session.commit("second")
        repo.create_branch("feature", commit2)

    before = sorted(repo.list_branches())
    expired = repo.expire_snapshots(
        future, delete_expired_branches=True, delete_expired_tags=False
    )
    after = sorted(repo.list_branches())
    print(
        f"{name}: {before} -> expired {len(expired)} snapshots -> remaining branches: {after}"
    )


print("=== Same tip (both point to commit2) ===")
test_expire("v1 python", icechunk_v1.Repository.create(icechunk_v1.in_memory_storage()))
test_expire(
    "v2 spec=1",
    icechunk.Repository.create(icechunk.in_memory_storage(), spec_version=1),
)
test_expire(
    "v2 spec=2",
    icechunk.Repository.create(icechunk.in_memory_storage(), spec_version=2),
)

print("\n=== Separate tips (feature->commit1, main->commit2) ===")
test_expire(
    "v1 python",
    icechunk_v1.Repository.create(icechunk_v1.in_memory_storage()),
    separate_tips=True,
)
test_expire(
    "v2 spec=1",
    icechunk.Repository.create(icechunk.in_memory_storage(), spec_version=1),
    separate_tips=True,
)
test_expire(
    "v2 spec=2",
    icechunk.Repository.create(icechunk.in_memory_storage(), spec_version=2),
    separate_tips=True,
)
```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in icechunk.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt, returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [ ] Recent environment — the issue occurs with the latest version of icechunk and its dependencies.

### Relevant log output

```Python

```

### Anything else we need to know?

_No response_

### Environment

<details>

</details>

### PR DESCRIPTION
**Pull request by dcherian**
Closes #1520 
Closes #1421 

Also add a boatload of V1 quirks to the model

### CODE REVIEW

File: icechunk/src/ops/gc.rs [hunk 1]
```diff
@@ -963,6 +963,23 @@ async fn expire_v2_one_attempt(
         repo_info.branches()?.map(|(_, id)| id).collect();
     let main_pointee = repo_info.resolve_branch(Ref::DEFAULT_BRANCH)?;
 
+    // All non-root snapshots old enough to be considered expired, regardless of
```
Comment (dcherian) [inline icechunk/src/ops/gc.rs:966]: @paraseba was this an intentional change? This is the cause of different behaviour in #1520

Comment (paraseba) [reply icechunk/src/ops/gc.rs:966]: I don't think it  was intentional, I prefer the v1 behavior described in #1520 . We can never expire the `main` branch, but it's ok for others.

File: icechunk/src/ops/gc.rs [hunk 2]
```diff
@@ -963,6 +963,23 @@ async fn expire_v2_one_attempt(
...
+                Some(Ok(si.id))
+            }
+            Ok(_) => None,
+            Err(e) => Some(Err(e)),
+        })
+        .try_collect()?;
+
     debug!("Calculating released snapshots");
     let released_snapshots: HashSet<SnapshotId> = repo_info
         .all_snapshots()?
```
Comment (dcherian) [inline icechunk/src/ops/gc.rs]: Filter `expires_snapshot_ids` instead?

File: icechunk-python/tests/test_stateful_repo_ops.py [hunk 3]
```diff
@@ -485,11 +525,27 @@ def garbage_collect(
...
+            # for kept snapshots whose parent was GC'd.
+            for c in self.commits.values():
+                if c.parent_id is not None and c.parent_id in deleted:
+                    c.parent_id = self.initial_snapshot_id
+        else:
+            # V1 doesn't rewrite parent pointers, so commits whose parents
+            # were GC'd have broken ancestry and are effectively unusable.
+            # Remove them from commits so we don't try to use them
+            while True:
+                orphaned = {
```
Comment (dcherian) [inline icechunk-python/tests/test_stateful_repo_ops.py]: walrus here?

File: icechunk-python/tests/test_stateful_repo_ops.py [hunk 4]
```diff
@@ -784,6 +851,9 @@ def create_branch(self, name: str, commit: str) -> str:
     @rule(name=ref_name_text, commit_id=commits, target=tags)
     def create_tag(self, name: str, commit_id: str) -> str:
         note(f"Creating tag {name!r} for commit {commit_id!r}")
+        # V1 expired snapshots stay on disk so create_tag succeeds, but
+        # the model no longer tracks their store contents.
+        assume(self.model.spec_version >= 2 or commit_id in self.model.commits)
```
Comment (dcherian) [inline icechunk-python/tests/test_stateful_repo_ops.py]:
```suggestion
        assume(not(self.model.spec_version == 1  and commit_id not in self.model.commits))
```
